from .Betray            import Betray
from .Blind             import Blind
from .Burn              import Burn
from .Chained           import Chained
from .Charm             import Charm
from .Coagulation       import Coagulation
from .CorpseExplosion   import CorpseExplosion
from .Corruption        import Corruption
from .Curse             import Curse
from .Despair           import Despair
from .Dull              import Dull
from .ElectricalShort   import ElectricalShort
from .Fatigue           import Fatigue
from .Frostbite         import Frostbite
from .Haze              import Haze
from .LivingBomb        import LivingBomb
from .Obey              import Obey
from .Overweight        import Overweight
from .Panic             import Panic
from .Peace             import Peace
from .Poison            import Poison
from .Recharge          import Recharge
from .Rigidity          import Rigidity
from .Shock             import Shock
from .Slow              import Slow
from .Spore             import Spore
from .Stun              import Stun
from .Vulnerable        import Vulnerable
from .Weak              import Weak
from .Web               import Web
################################################################################
